deepsort:
  deepsort_cfg_path: "E:/Deepsort_ReID_Tracker/configs/deep_sort.yaml"

yolo:
  model_path: "E:/Deepsort_ReID_Tracker/models/yolo/weights/yolo11n.pt"

extractor:
  extractor_name: "osnet_x1_0"
  extractor_path: "E:/Deepsort_ReID_Tracker/models/feature_extractor/weights/osnet_x1_0_imagenet.pth"

reid_tracker:
  LOST_THRESHOLD: 15
  frame_batch_size: 15
  limit_min_L2distance: 0.43
  min_conf: 0.7
  reinforce_tensity: 1
  sample_density: 5

person_database:
  base_size: 5
  recent_size: 5